NinjaSagab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
]

web/urls.py
from django.urls import path
from .views import index, predict_word

app_name = "web";

urlpatterns = [
    path(r'', index, name='index'),
    path(r'predict', predict_word, name='predict_word')
]

web/models.py
from django.db import models

# Create your models here.

web/forms.py
from django import forms

class Input_Form(forms.Form):
    attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'form-control',
        'id': 'predict',
        'placeholder':'Masukkan pesan disini...'
    }

    input = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=attrs))

web/views.py
from django.shortcuts import render
from django.http import JsonResponse
from lib.hate_speech_filter import classify
from .forms import Input_Form
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

def index(request):
    return render(request, 'halaman.html', {'form': Input_Form})


@csrf_exempt
def predict_word(request):    
    form = Input_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        str_input = request.POST['input']
        category, hs_probability, non_hs_probability = classify(str_input)
        if category == 1:
        	category = "Hate Speech"
        elif category == 2:
        	category = "Non Hate Speech"
        else:
        	category = "Undecided"
        	hs_probability = 0
        	non_hs_probability = 0
        return JsonResponse({
            'category': category,
            'hs_probability': hs_probability*100,
            'non_hs_probability': non_hs_probability*100
            })

web/templates/halaman.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>HALO.id : Hate Speech Filter Online Indonesia</title>
    <style type="text/css">
      body {
        padding-top: 54px;
      }

      @media (min-width: 992px) {
        body {
          padding-top: 56px;
        }
      }

      .business-header {
        height: 70vh;
        min-height: 300px;
        background: url('https://martechtoday.com/wp-content/uploads/2017/02/network-machine-learning-ss-1920.jpg') center center no-repeat scroll;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        background-size: cover;
        -o-background-size: cover;
      }

      .card {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">HALO.id</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>

    <!-- Header with Background Image -->
    <header class="business-header">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <h1 class="display-3 text-center text-white mt-4">Hate Speech Filter Indonesia</h1>
            <h5 class="display-7 text-center text-white mt-4">Hate Speech Detector powered by Machine Learning Algorithm</h1>
          </div>
        </div>
      </div>
    </header>

    <!-- Page Content -->
    <div class="container">

      <div class="row">
        <div class="col-sm-8">
          <h2 class="mt-4">Tentang Proyek</h2>
          <p>
            Dewasa ini, pesan ujaran kebencian semakin marak disuarakan di berbagai media sosial, hal ini menyebabkan rusaknya atmosfir masyarakat Indonesia
            dalam berkehidupan sosial secara daring. Proyek ini dibuat untuk membantu masyarakat indonesia dalam mengidentfikasi pesan-pesan yang bersifat ujaran kebencian. 
          </p>
          <p>Dibantu oleh prinsip machine learning dan naive bayes, kami dapat membuat sebuah perangkat yang dapat mengidentifikasi apakah sebuah pesan merupakan sebuah ujaran kebencian atau tidak, 
            menggunakan dataset yang telah terverifikasi.
          </p>
          <br>
          <div class="form-group">
            {{ form }}
          </div>
          <button type="button" class="btn btn-primary btn-lg" onClick="predictWord($('#predict').val())">Go! &raquo;</button>
          <div id="loading">
            
          </div>
          <br>
        </div>
        <div class="col-sm-4">
          <h2 class="mt-4">Proyek ini dibuat oleh :</h2>
          <ul>
            <li>Anindito Bhagawanta</li>
            <li>Ibnu Sofian Firdaus</li>
            <li>Mohamad Mahendra</li>
          </ul>
        </div>
      </div>
      <!-- /.row -->
      </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-4 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Ninja Sagab 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    {% block javascript %}
    <script>
        var predictWord = function(word) {
          $('#loading').html("Loading...");
            $.ajax({
                method: "POST",
                url: '{% url "web:predict_word" %}',
                data: { input: word },
                success: function (data) {
                    var category = data['category'];
                    var hsProbability = data['hs_probability'];
                    var nonHsProbability = data['non_hs_probability'];
                    var text = "Category: " + category + ", Hate Speech Probability: " + hsProbability + " points, Non Hate Speech Probability: " + nonHsProbability + " points";
                    $("#loading").html(text);
                },
                error: function (error) {
                    $("#loading").html("An error has occured. Please try again.");
                }
            });
        };
    </script>
    {% endblock %}
  </body>
</html>